name: Image Builder

on:
  push:
    tags: 
    - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          repository: phosae/kubetools
          path: ./kubetools

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: zengxu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub 
        uses: docker/build-push-action@v3
        with:
          context: ./kubetools
          tags: |
            zengxu/kubetools,zengxu/kubetools:${{github.ref_name}}
          platforms: |
            linux/amd64,linux/arm64
          push: true
